### ISSUE TITLE
VirtualBox instructions

### ISSUE THREAD

**Issue by ASMHSE** [LensPlaysGames/LensorOS#8]
VirtualBox instructions forget to mention that Com1 must be enabled.

**Comment by LensPlaysGames** [comment]
Thank you for bringing this to my attention!! I'll be sure to remedy that, and I'll close the issue when I do. <3

**Comment by LensPlaysGames** [comment]
Fixed in https://github.com/LensPlaysGames/LensorOS/commit/dfce5337c723949d8dce6877775e156392a3f120
